package c6h2cl2.YukariLib.ASM

import c6h2cl2.YukariLib.YukariLibCore
import com.google.common.eventbus.EventBus
import net.minecraftforge.fml.common.DummyModContainer
import net.minecraftforge.fml.common.LoadController
import net.minecraftforge.fml.common.ModMetadata

/**
 * @author C6H2Cl2
 */
class YukariLibDummyModContainer: DummyModContainer(ModMetadata()) {
    init {
        val meta = metadata
        meta.modId = YukariLibCore.DOMAIN + "asm"
        meta.name = YukariLibCore.MOD_ID + "ASM"
        meta.version = YukariLibCore.Version
        meta.authorList.add("C6H2Cl2")
        meta.autogenerated = false
    }

    override fun registerBus(bus: EventBus, controller: LoadController): Boolean {
        bus.register(this)
        return true
    }
}