package c6h2cl2.YukariLib

import c6h2cl2.YukariLib.Client.TestResourcePack
import net.minecraftforge.fml.common.DummyModContainer
import net.minecraftforge.fml.common.ModMetadata

/**
 * @author C6H2Cl2
 */
class YukariLibModContainer: DummyModContainer(ModMetadata()) {
    init {
        val meta = metadata!!
        meta.modId = YukariLibCore.DOMAIN + "_dummy"
        meta.name = YukariLibCore.MOD_ID + "Dummy"
        meta.version = YukariLibCore.Version
        meta.authorList.add("C6H2Cl2")
        meta.autogenerated = false
    }

    override fun getCustomResourcePackClass(): Class<*> {
        return TestResourcePack::class.java
    }
}