package c6h2cl2.YukariLib

import c6h2cl2.YukariLib.Event.YukariLibEventHandler
import cpw.mods.fml.common.Mod
import cpw.mods.fml.common.Mod.EventHandler
import cpw.mods.fml.common.ModMetadata
import cpw.mods.fml.common.event.FMLInitializationEvent
import cpw.mods.fml.common.event.FMLPreInitializationEvent
import net.minecraft.client.Minecraft
import net.minecraft.launchwrapper.Launch
import net.minecraftforge.common.MinecraftForge
import java.io.BufferedReader
import java.io.InputStreamReader
import java.net.URL

/**
 * @author C6H2Cl2
 */
@Mod(modid = YukariLibCore.MOD_ID,version = YukariLibCore.Version,useMetadata = true)
class YukariLibCore {
    companion object{
        const val MOD_ID = "YukariLib"
        const val DOMAIN = "yukarilib"
        const val Version = "1.0.3"
        @Mod.Metadata
        var metadata : ModMetadata? = null
    }

    @Mod.EventHandler
    fun preinit(event: FMLPreInitializationEvent){
        if (event.side.isClient) {
            val userName = Minecraft.getMinecraft().session.username
            val url = URL("https://api.mojang.com/users/profiles/minecraft/$userName")
            BufferedReader(InputStreamReader(url.openStream())).use {
                if (it.readLine() == null){
                    if(Launch.blackboard["fml.deobfuscatedEnvironment"]?.equals(true) == false){
                        throw PlayerNotOfficialPurchasedException()
                    }
                }
            }
        }
        loadMeta()
    }

    @EventHandler
    fun init(event: FMLInitializationEvent){
        MinecraftForge.EVENT_BUS.register(YukariLibEventHandler())
    }

    private fun loadMeta(){
        val meta = metadata as ModMetadata
        meta.modId = DOMAIN
        meta.name = MOD_ID
        meta.version = Version
        meta.authorList.add("C6H2Cl2")
        meta.credits = "This mod includes Kotlin STDLib and Jetbrains Annotations.\nThey are licensed under the Apache 2 OSS License."
        meta.description = "This mod is an wrapper for mods made from KotlinLanguage and provides some utils."
        meta.autogenerated = false
    }
}