package c6h2cl2.YukariLib

import cpw.mods.fml.common.Mod
import cpw.mods.fml.common.ModMetadata
import cpw.mods.fml.common.event.FMLPreInitializationEvent

/**
 * @author C6H2Cl2
 */
@Mod(modid = "YukariLib",useMetadata = true)
class YukariLibCore {
    companion object{
        val MOD_ID = "YukariLib"
        val DOMAIN = MOD_ID.toLowerCase()
        val Version = "1.0.0"
        @Mod.Metadata
        var metadata : ModMetadata? = null
    }

    @Mod.EventHandler
    fun preinit(event: FMLPreInitializationEvent){
        loadMeta()
    }

    private fun loadMeta(){
        val meta = metadata as ModMetadata
        meta.modId = DOMAIN
        meta.name = MOD_ID
        meta.version = Version
        meta.authorList.add("C6H2Cl2")
        meta.credits = "This mod includes Kotlin STDLib and Jetbrains Annotations.\nThey are licensed under the Apache 2 OSS License."
        meta.description = "This mod is an wrapper for mods made from KotlinLanguage and provides some utils."
        meta.autogenerated = false
    }
}