package c6h2cl2.YukariLib

import c6h2cl2.YukariLib.Util.Register.RegisterHandler
import net.minecraft.client.Minecraft
import net.minecraft.launchwrapper.Launch
import net.minecraftforge.fml.common.Mod
import net.minecraftforge.fml.common.ModMetadata
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent
import java.io.BufferedReader
import java.io.InputStreamReader
import java.net.URL

/**
 * @author C6H2Cl2
 */
@Mod(modid = YukariLibCore.MOD_ID, version = YukariLibCore.Version, useMetadata = true)
class YukariLibCore {
    companion object {
        const val MOD_ID = "YukariLib"
        const val DOMAIN = "yukarilib"
        const val Version = "1.0.2.1"
        @JvmField
        @Mod.Metadata
        var metadata: ModMetadata? = null
    }

    @Mod.EventHandler
    fun preinit(event: FMLPreInitializationEvent) {
        if (event.side.isClient) {
            val userName = Minecraft.getMinecraft().session.username
            val url = URL("https://api.mojang.com/users/profiles/minecraft/$userName")
            BufferedReader(InputStreamReader(url.openStream())).use {
                if (it.readLine() == null){
                    if(Launch.blackboard["fml.deobfuscatedEnvironment"]?.equals(true) == false){
                        throw PlayerNotOfficialPurchasedException()
                    }
                }
            }
        }
        loadMeta()
        val register = RegisterHandler(MOD_ID)
        register.build(Register)
        register.handle(event)
    }

    private fun loadMeta() {
        val meta = metadata as ModMetadata
        meta.modId = MOD_ID
        meta.name = MOD_ID
        meta.version = Version
        meta.authorList.add("C6H2Cl2")
        meta.credits = "This mod includes Kotlin STDLib and Jetbrains Annotations.They are licensed under the Apache 2 OSS License."
        meta.description = "This mod is an wrapper for mods made from KotlinLanguage and provides some utils."
        meta.autogenerated = false
    }
}